# Generated by Django 5.0.5 on 2024-05-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('TID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1500)),
                ('supName', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='TestThesis',
        ),
    ]
