# Generated by Django 4.2.13 on 2024-05-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='required', max_length=30)),
                ('lastname', models.CharField(default='required', max_length=30)),
                ('email', models.EmailField(default='required (@students.cdu.edu.au)', max_length=50)),
                ('password', models.CharField(default='required', max_length=30)),
                ('studentid', models.CharField(default='required', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ThesisApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThesisID', models.CharField(default='ThesisID', max_length=10)),
                ('GroupNumber', models.CharField(default='Group Number', max_length=10)),
                ('StudentID', models.CharField(default='Student ID', max_length=10)),
            ],
        ),
    ]
