# Generated by Django 4.2.11 on 2024-05-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0002_project_delete_testthesis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='TID',
            new_name='tid',
        ),
    ]
