# Generated by Django 4.2.13 on 2024-05-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0002_student_thesisapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisapplication',
            name='GroupNumber',
            field=models.CharField(default='Group Number', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='thesisapplication',
            name='StudentID',
            field=models.CharField(default='Student ID', max_length=10, unique=True),
        ),
    ]
