# Generated by Django 4.2.11 on 2024-05-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0003_alter_thesisapplication_groupnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='thesisapplication',
            name='ThesisID',
            field=models.CharField(default='ID', max_length=50),
        ),
    ]
