# Generated by Django 4.2.13 on 2024-05-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0004_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
