# Generated by Django 4.2.13 on 2024-05-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0004_notification_alter_thesisapplication_thesisid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notification',
        ),
    ]
