# Generated by Django 4.2.13 on 2024-05-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0006_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='messages',
            new_name='content',
        ),
    ]
