# Generated by Django 4.2.13 on 2024-05-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0008_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('SUPERVISOR', 'Supervisor')], default='SUPERVISOR', max_length=50),
        ),
    ]
