# Generated by Django 4.2.13 on 2024-05-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0009_remove_accounts_is_loggedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesisapplication',
            name='GroupNumber',
        ),
    ]
