# Generated by Django 4.2.13 on 2024-05-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0009_accounts_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='role',
            field=models.CharField(choices=[('COORDINATOR', 'Coordinator'), ('STUDENT', 'Student'), ('SUPERVISOR', 'Supervisor')], default='SUPERVISOR', max_length=50),
        ),
    ]
