# Generated by Django 4.2.13 on 2024-05-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0013_alter_accounts_role_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
