# Generated by Django 4.2.13 on 2024-05-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0014_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='notification',
        ),
    ]
