# Generated by Django 4.2.13 on 2024-05-28 07:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0015_requests_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='message',
        ),
        migrations.AddField(
            model_name='requests',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='requests',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='requests',
            name='who_from',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='who_from_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
