# Generated by Django 4.2.13 on 2024-05-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0016_remove_requests_message_requests_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
