# Generated by Django 4.2.13 on 2024-05-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0018_project_message_alter_project_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='message',
        ),
    ]
