# Generated by Django 4.2.13 on 2024-05-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0019_remove_project_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_request',
            field=models.BooleanField(default=True),
        ),
    ]
