# Generated by Django 4.2.13 on 2024-05-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0020_project_is_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='content',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='who_from',
        ),
        migrations.AlterField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
