# Generated by Django 4.2.13 on 2024-05-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0021_remove_requests_content_remove_requests_timestamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
