# Generated by Django 4.2.13 on 2024-05-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2_app', '0024_alter_project_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tid',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
